/**
 * Alternate app icons — a one-call adapter over `expo-alternate-app-icons`.
 *
 * THE DEPENDENCY IS NOT INSTALLED YET, ON PURPOSE. It autolinks a pod and its
 * config plugin only does its work during `expo prebuild`, which this project
 * never runs for iOS (the Xcode project is hand-maintained; see CLAUDE.md).
 * Adding it to `app.json`'s plugin list before the package exists would break
 * `expo start` for everyone, so the wiring is left to the maintainer:
 *
 *   1. `npm i expo-alternate-app-icons`
 *   2. add the plugin block to `app.json` pointing at `assets/icons/*.png`
 *      (Android is then regenerated by EAS and works)
 *   3. iOS: add the `CFBundleAlternateIcons` entries + the icon files to the
 *      Xcode project BY HAND — prebuild is never run here
 *
 * Until then `supported()` answers false and the picker says so, which is also
 * exactly what a dev client that predates the rebuild needs to see. The require
 * is guarded the same way `analytics.ts` guards Firebase.
 */
type IconModule = {
  supportsAlternateIcons: boolean;
  getAppIconName(): string;
  setAlternateAppIcon(name: string | null): Promise<string>;
};

let mod: IconModule | null = null;
try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  mod = require('expo-alternate-app-icons') as IconModule;
} catch {
  mod = null;
}

/**
 * The variants, named by their accent. `null` is the shipped OT icon — it is
 * never paywalled, because taking a paid icon away must always be possible.
 */
export const APP_ICONS = ['default', 'orange', 'purple', 'teal'] as const;
export type AppIconName = (typeof APP_ICONS)[number];

export function supported(): boolean {
  return mod?.supportsAlternateIcons === true;
}

export function currentIcon(): AppIconName {
  const name = mod?.getAppIconName();
  return (APP_ICONS as readonly string[]).includes(name ?? '') ? (name as AppIconName) : 'default';
}

/** Resolves to whether it took. Never throws: a refused icon is not a crash. */
export async function setIcon(name: AppIconName): Promise<boolean> {
  if (!mod?.supportsAlternateIcons) return false;
  try {
    await mod.setAlternateAppIcon(name === 'default' ? null : name);
    return true;
  } catch {
    return false;
  }
}
