/**
 * The exact file set + column headers of a real TV Time GDPR export (57 files),
 * so our export ZIP is structurally identical. Generated from a real export —
 * headers only, no data.
 */
export const TVTIME_HEADERS: Record<string, string[]> = {
  '_appsflyer_ids.csv': ['user_id', 'appsflyer_device_id', 'created_at', 'updated_at'],
  '_user_creation_ip.csv': ['user_id', 'ip_address', 'created_at'],
  'access_token.csv': ['cpt', 'id', 'user_id', 'app_id', 'access_token', 'created_at', 'updated_at'],
  'auth-prod-login.csv': ['username', 'encrypted_token', 'range_key', 'provider', 'encrypted_secret', 'external_id', 'hash_key', 'user_id', 'email', 'password_hash'],
  'comments-prod-comments.csv': ['is_spoiler', 'sort_key', 'uuid', 'type', 'created_at', 'replies', 'comment_uuid', 'reply_count', 'entity_type', 'report_count', 'movie_name', 'updated_at', 'entity_uuid', 'like_count', 'image', 'text', 'user_id', 'spoiler_count', 'parent_uuid', 'inappropriate_count', 'lang', 'comment_id', 'tenant', 'expires_at', 'last_read', 'series_name'],
  'device_data.csv': ['device_id', 'name', 'value', 'created_at', 'updated_at', 'id'],
  'device_token.csv': ['created_at', 'device', 'parse_installation_id', 'version_code', 'fcm_registration_token', 'id', 'user_id', 'app_version', 'device_token', 'updated_at'],
  'emotions-3-prod-episode_votes.csv': ['episode_id', 'vote_key', 'user_id', 'series_name', 'season_number', 'episode_number'],
  'emotions-live-votes.csv': ['vote_key', 'uuid', 'episode_id', 'user_id', 'movie_name'],
  'episode_comment.csv': ['tv_show_name', 'id', 'episode_id', 'unappropriate_count', 'nb_likes', 'spoiler_count', 'highlight_level', 'valid', 'episode_season_number', 'comment_type', 'same_ip_likes', 'episode_number', 'updated_at', 'posted_on_fb', 'lang', 'parent_comment_id', 'depth', 'extended_comment', 'source', 'nb_points', 'user_id', 'comment', 'created_at', 'posted_on_twitter'],
  'episode_comment_like.csv': ['user_id', 'episode_comment_id', 'created_at', 'updated_at', 'source'],
  'followed_tv_show.csv': ['created_at', 'active', 'diffusion', 'notification_type', 'archived', 'tv_show_name', 'user_id', 'tv_show_id', 'notification_offset', 'updated_at', 'folder_id'],
  'followed_tv_show_source.csv': ['user_id', 'tv_show_id', 'source', 'created_at', 'updated_at', 'tv_show_name'],
  'friend.csv': ['user_id', 'friend_id', 'created_at', 'updated_at', 'affinity'],
  'gdpr_requests.csv': ['id', 'created_at', 'updated_at', 'locked', 's3_key', 'user_id', 'source', 'data_generated', 'error_message'],
  'install_tracking.csv': ['id', 'user_id', 'source', 'name', 'value', 'created_at', 'updated_at'],
  'ip_address.csv': ['ip_address', 'city_name', 'longitude', 'updated_at', 'region_name', 'country_name', 'zip_code', 'hits', 'created_at', 'user_id', 'country_code', 'latitude', 'timezone'],
  'lists-prod-lists.csv': ['user_id', 'type', 'is_public', 'name', 'description', 's_key', 'ordering', 'created_at', 'objects', 'lists'],
  'meme.csv': ['medium_url', 'episode_comment_id', 'width', 'url', 'clean_version_medium_url', 'gif_medium_url', 'meme_id', 'updated_at', 'id', 'clean_version_url', 'captions', 'gif_url', 'external', 'type', 'created_at', 'has_captions', 'small_url', 'clean_version_small_url', 'blurred_version_url', 'gif_small_url', 'signature', 'has_stickers', 'has_drawing', 'height'],
  'notifications-prod-notifications.csv': ['is_read', 'user_id', 'type', 'read', 'time', 'web_url', 'url', 'date', 'objects', 'data', 'badge_name', 'image', 'badge', 'text', 'object_id', 'html_text', 'sound', 'title', 'object_type'],
  'object_like.csv': ['updated_at', 'user_id', 'object_type', 'object_id', 'source', 'created_at'],
  'ratings-3-prod-episode_votes.csv': ['episode_id', 'vote_key', 'series_name', 'season_number', 'episode_number', 'user_id'],
  'ratings-live-votes.csv': ['uuid', 'vote_key', 'episode_id', 'movie_name', 'user_id'],
  'recommendations-prod-user-scores.csv': ['tv_shows', 'user_mean', 'user_id', 'user_variance'],
  'recommendations-prod-user-shows.csv': ['watched_show_ids', 'user_id'],
  'refresh_token.csv': ['user_id', 'device_id', 'token', 'blacklisted', 'created_at', 'updated_at'],
  'routing-prod-users.csv': ['username', 'image_url', 'aws_region', 'created_at', 'updated_at', 'user_id'],
  'show_addiction_score.csv': ['daily_score', 'weekly_score', 'monthly_score', 'tv_show_name', 'user_id', 'tv_show_id', 'last_action_timestamp'],
  'show_character_episode_vote.csv': ['show_character_id', 'episode_number', 'episode_id', 'created_at', 'updated_at', 'fb_action_id', 'tv_show_name', 'episode_season_number', 'user_id'],
  'show_seen_episode_latest.csv': ['user_id', 'tv_show_id', 'episode_id', 'created_at', 'updated_at', 'tv_show_name'],
  'stats-prod-cache.csv': ['stat_type', 'type', 'interaction_type', 'stats', 'version', 'user_id', 'entity_type', 'timestamp', 'watched_episodes_per_week', 'quick_watches', 'biggest_marathons', 'watched_episodes_per_month'],
  'tracking-deployment-prod-tracks.csv': ['created_at', 'day', 'user_id'],
  'tracking-prod-count-by-timeframe.csv': ['count', 'expires_at', 'runtime', 'user_id', 'type'],
  'tracking-prod-records-v2.csv': ['s_no', 'ep_no', 'runtime', 'series_name', 'episode_number', 'created_at', 'user_id', 'ep_id', 'key', 'season_number', 'gsi', 's_id', 'episode_id', 'updated_at', 'total_movies_runtime', 'series_follow_count', 'total_series_runtime', 'ep_watch_count', 'movie_watch_count', 'is_archived', 'is_for_later', 'uuid', 'is_followed', 'followed_at', 'most_recent_ep_watched', 'is_unitary', 'bulk_type', 'rewatch_count'],
  'tracking-prod-records.csv': ['type', 'series_id', 'watch_count', 'user_id', 'type-uuid-n', 'updated_at', 'created_at', 'uuid', 'series_name', 'watches', 'runtime', 'alpha_range_key', 'release_date', 'entity_type', 'movie_name', 'follow_date_range_key', 'release_date_range_key', 'episode_number', 'watch_date', 'season_number', 'episode_id', 'series_uuid', 'rewatch_count', 'total_series_runtime', 'total_movies_runtime', 'watch_date_range_key', 'country', 'bulk_type', 'watched_episode_range_key', 'unitarian'],
  'tv_show_user_emotion_count.csv': ['tv_show_id', 'user_id', 'emotion_id', 'count', 'created_at', 'updated_at', 'tv_show_name'],
  'user.csv': ['name', 'nb_weeks_active', 'fake_account', 'twitter_connect_time', 'hash', 'default_diffusion', 'nb_months_active', 'language', 'publish_on_ticker', 'last_updated', 'excluded_networks', 'newsletter_activated', 'timezone', 'twitter_oauth_token_secret', 'version_number', 'created_at', 'badge', 'facebook_id', 'password_new', 'twitter_id', 'twitter_oauth_token', 'last_opened', 'fb_connect_time', 'backward_days', 'fb_access_token', 'posted_on_wall', 'device_token', 'last_time_synced_drive', 'tumblr_id', 'notif_friend_join', 'fb_expiration_date', 'default_notification_offset', 'nb_days_active', 'id', 'publish_on_twitter', 'tumblr_oauth_token_secret', 'excluded_shows', 'public_profile', 'tumblr_oauth_token', 'password', 'updated_at', 'automatic_account', 'mail', 'last_time_loaded_towatch', 'notif_news', 'notif_webseries_reco', 'notif_webseries_new_video', 'mail_status'],
  'user_badge.csv': ['user_id', 'badge_id', 'created_at', 'updated_at'],
  'user_connection.csv': ['source', 'user_id', 'date', 'created_at', 'updated_at'],
  'user_device.csv': ['device_id', 'version_code', 'created_at', 'updated_at', 'user_id'],
  'user_facebook_data.csv': ['facebook_id', 'timezone', 'created_at', 'updated_at', 'location', 'user_id', 'name', 'username', 'gender', 'birthday'],
  'user_last_updated.csv': ['user_id', 'last_updated', 'created_at', 'updated_at'],
  'user_leaderboard.csv': ['user_id', 'leaderboard_id', 'score', 'created_at', 'updated_at'],
  'user_object_last_action_date.csv': ['last_action_date', 'created_at', 'updated_at', 'user_id', 'object_type', 'object_id', 'action'],
  'user_personal_data.csv': ['id', 'user_id', 'name', 'value', 'created_at', 'updated_at'],
  'user_platform.csv': ['user_id', 'registered_on', 'iphone_cnt', 'ipad_cnt', 'android_cnt', 'web_cnt', 'created_at', 'updated_at'],
  'user_poll.csv': ['poll_id', 'poll_choice_id', 'lang_taken', 'created_at', 'updated_at', 'user_id'],
  'user_quiz.csv': ['created_at', 'result_image_url', 'user_id', 'quiz_id', 'finished', 'score', 'updated_at', 'avg_time', 'teammate_id', 'question_group', 'lang_taken'],
  'user_quiz_answer.csv': ['user_id', 'quiz_question_id', 'quiz_question_answer_id', 'score', 'created_at', 'updated_at', 'time'],
  'user_session.csv': ['created_at', 'medium', 'content', 'id', 'platform', 'source', 'campaign', 'user_id', 'deeplink', 'updated_at'],
  'user_setting.csv': ['name', 'value', 'created_at', 'updated_at', 'id', 'user_id'],
  'user_social_data.csv': ['screen_name', 'picture_url', 'created_at', 'updated_at', 'image_id', 'gender', 'birthday', 'user_id'],
  'user_statistics.csv': ['nb_comments', 'nb_reviews', 'nb_likes', 'score', 'user_id', 'time_spent', 'nb_friends', 'nb_memes', 'id', 'updated_at', 'created_at', 'nb_shows_followed', 'nb_episodes_watched'],
  'user_tv_show_data.csv': ['is_followed', 'is_favorited', 'nb_episodes_seen', 'tv_show_name', 'user_id', 'tv_show_id'],
  'watched_on_episode.csv': ['tv_show_name', 'episode_season_number', 'episode_number', 'user_id', 'episode_id', 'watched_on_source_id', 'created_at', 'updated_at'],
  'webhook_data.csv': ['updated_at', 'data_processed', 'user_id', 'id', 'source', 'external_id', 'data_received', 'created_at'],
  'where-to-watch-prod-table.csv': ['user_id', 'id', 'vote_type', 'created_at', 'network_platform', 'type', 'hash_key', 'range_key', 'episode_id', 'series_name', 'episode_number', 'season_number'],
};
